ThoughtStorm/CVRD

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_DPA_Sub_Type__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Development_Permit.recordType-meta.xml
force-app/main/default/objects/MUSW__Master_Fee_List__c/fields/CVRD_DS_Application_DP_Sub_Type__c.field-meta.xml
force-app/main/default/objects/MUSW__Master_Fee_List__c/recordTypes/MUSW__Application_Fee.recordType-meta.xml

[DevOps Center] Merge WI-000264 to QA

---

force-app/main/default/flows/CVRD_DS_Create_Fee_Application.flow-meta.xml

[DevOps Center] Merge WI-000265 to QA

---

force-app/main/default/flexipages/Application_Record_Page1.flexipage-meta.xml
force-app/main/default/layouts/MUSW__Application2__c-Strata Conversion.layout-meta.xml

[DevOps Center] Merge WI-000270 to QA

---

force-app/main/default/globalValueSets/CVRD_DS_Sub_Type.globalValueSet-meta.xml
force-app/main/default/globalValueSets/MUSW__Review_Completed_Actions.globalValueSet-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Completed_Approval__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Land_Title_Number__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Land_Title_Registration_Date__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Review_Outcome__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Sub_Type__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Completed_Action__c.field-meta.xml
force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Status__c.field-meta.xml

[DevOps Center] Merge WI-000274 to QA

---

force-app/main/default/flexipages/Application_Record_Page1.flexipage-meta.xml
force-app/main/default/flows/Application_Journey.flow-meta.xml

[DevOps Center] Merge WI-000281 to QA

---

force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_Approval.approvalProcess-meta.xml
force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_General_Manager_V2.approvalProcess-meta.xml
force-app/main/default/globalValueSets/CVRD_DS_Sub_Type.globalValueSet-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Sub_Type__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Cannabis_License.recordType-meta.xml
force-app/main/default/objects/MUSW__Master_Fee_List__c/recordTypes/MUSW__Application_Fee.recordType-meta.xml

[DevOps Center] Merge WI-000282 to QA

---

force-app/main/default/flows/CVRD_DS_Review_Update_Milestone_Status.flow-meta.xml
force-app/main/default/globalValueSets/MUSW__Milestone_Completed_Actions.globalValueSet-meta.xml
force-app/main/default/objects/MUSW__Milestone__c/recordTypes/MUSW__Admin_Review_Milestone.recordType-meta.xml

[DevOps Center] Merge WI-000283 to QA

---

force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_Approval.approvalProcess-meta.xml
force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_General_Manager_V2.approvalProcess-meta.xml
force-app/main/default/flows/Application_Journey.flow-meta.xml

[DevOps Center] Merge WI-000284 to QA

---

force-app/main/default/globalValueSets/MUSW__Milestone_Completed_Actions.globalValueSet-meta.xml
force-app/main/default/globalValueSets/MUSW__Review_Completed_Actions.globalValueSet-meta.xml

[DevOps Center] Merge WI-000285 to QA

---

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Planner__c.field-meta.xml

[DevOps Center] Merge WI-000287 to QA

---

force-app/main/default/quickActions/MUSW__Application2__c.CVRD_DS_Upload_Decision_File.quickAction-meta.xml

[DevOps Center] Merge WI-000289 to QA

---

force-app/main/default/flexipages/Application_Record_Page1.flexipage-meta.xml
force-app/main/default/layouts/MUSW__Application2__c-Development Variance Permit %28DVP%29 Layout.layout-meta.xml

[DevOps Center] Merge WI-000288 to QA

---

force-app/main/default/aura/GeneratePDF/GeneratePDF.cmp
force-app/main/default/aura/GeneratePDF/GeneratePDF.cmp-meta.xml
force-app/main/default/aura/GeneratePDF/GeneratePDF.design
force-app/main/default/aura/GeneratePDF/GeneratePDFController.js
force-app/main/default/classes/CVRD_DS_Get_Required_Submissions.cls
force-app/main/default/classes/CVRD_DS_Get_Required_Submissions.cls-meta.xml
force-app/main/default/flows/Upload_Submission_Requests.flow-meta.xml

[DevOps Center] Merge WI-000294 to QA

---

force-app/main/default/layouts/MUSW__Proceeding2__c-MUSW__Proceeding Layout.layout-meta.xml
force-app/main/default/objects/MUSW__Proceeding2__c/fields/MUSW__Type__c.field-meta.xml
force-app/main/default/objects/MUSW__Proceeding_Agenda_Item__c/fields/CVRD_DS_Outcome__c.field-meta.xml

[DevOps Center] Merge WI-000299 to QA

---

force-app/main/default/objects/CVRD_DS_Proceeding_OutcomeMapping__mdt/CVRD_DS_Proceeding_OutcomeMapping__mdt.object-meta.xml
force-app/main/default/objects/CVRD_DS_Proceeding_OutcomeMapping__mdt/fields/CVRD_DS_ApplicationType__c.field-meta.xml
force-app/main/default/objects/CVRD_DS_Proceeding_OutcomeMapping__mdt/fields/CVRD_DS_OutcomeValue__c.field-meta.xml
force-app/main/default/objects/CVRD_DS_Proceeding_OutcomeMapping__mdt/fields/CVRD_DS_ProceedingType__c.field-meta.xml

[DevOps Center] Merge WI-000301 to QA

---

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_RCRS_classification__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Agricultural_Land_Reserve.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Board_of_Variance.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Cannabis_License.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Covenant_Amendment_or_Discharge.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Crown_Land_Referrals.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Development_Permit.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Development_Variance_Permit.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Flood_Management_Bylaw_Exemption.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Liquor_Cannabis_Licence_Referrals.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Minimum_Frontage_Exemption.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_OCP_Zoning_or_Land_Use_Bylaw_Amendment.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Phased_Development_Agreement.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Strata_Conversion.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Subdivision_Referral.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Telecommunication_Antenna_Structure.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Temporary_Use_Permit.recordType-meta.xml

[DevOps Center] Merge WI-000306 to QA

---

force-app/main/default/flows/Upload_Submission_Requests.flow-meta.xml

[DevOps Center] Merge WI-000307 to QA

---

force-app/main/default/layouts/MUSW__Proceeding2__c-MUSW__Proceeding Layout.layout-meta.xml

[DevOps Center] Merge WI-000309 to QA

---

force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_Approval.approvalProcess-meta.xml
force-app/main/default/globalValueSets/CVRD_DS_Sub_Type.globalValueSet-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Sub_Type__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Liquor_Cannabis_Licence_Referrals.recordType-meta.xml
force-app/main/default/objects/MUSW__Master_Fee_List__c/recordTypes/MUSW__Application_Fee.recordType-meta.xml

[DevOps Center] Merge WI-000310 to QA

---

force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_Approval.approvalProcess-meta.xml
force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_General_Manager_V2.approvalProcess-meta.xml
force-app/main/default/flexipages/Application_Record_Page1.flexipage-meta.xml
force-app/main/default/flexipages/CVRD_DS_BoardOfVarianceApplication_Record_Page11.flexipage-meta.xml
force-app/main/default/flexipages/CVRD_DS_DP_RecordPage.flexipage-meta.xml
force-app/main/default/flows/CVRD_DS_Application_Reconsideration_Letter.flow-meta.xml
force-app/main/default/globalValueSets/CVRD_DS_Sub_Type.globalValueSet-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Sub_Type__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Liquor_Cannabis_Licence_Referrals.recordType-meta.xml
force-app/main/default/objects/MUSW__Master_Fee_List__c/recordTypes/MUSW__Application_Fee.recordType-meta.xml

[DevOps Center] Merge WI-000314 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Complete_Hearing_Phase.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Update_Agenda_Item_OutCome.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Update_Planner_Review_to_Correction_Required.flow-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Agricultural_Land_Reserve.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Board_of_Variance.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Cannabis_License.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Covenant_Amendment_or_Discharge.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Crown_Land_Referrals.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Development_Permit.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Development_Variance_Permit.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Flood_Management_Bylaw_Exemption.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Minimum_Frontage_Exemption.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_OCP_Zoning_or_Land_Use_Bylaw_Amendment.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Phased_Development_Agreement.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Strata_Conversion.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Subdivision_Referral.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Telecommunication_Antenna_Structure.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Temporary_Use_Permit.recordType-meta.xml
force-app/main/default/objects/MUSW__Proceeding_Agenda_Item__c/compactLayouts/MUSW__Proceeding_Agenda_Item_Default.compactLayout-meta.xml
force-app/main/default/quickActions/MUSW__Application2__c.Complete_Hearing.quickAction-meta.xml

[DevOps Center] Merge WI-000316 to QA

---

force-app/main/default/flows/CVRD_DS_Create_Proceeding_Agenda_Item.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Update_Agenda_Item_OutCome.flow-meta.xml

[DevOps Center] Merge WI-000317 to QA

---

force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_Approval.approvalProcess-meta.xml

[DevOps Center] Merge WI-000318 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Journey.flow-meta.xml

[DevOps Center] Merge WI-000319 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Journey.flow-meta.xml

[DevOps Center] Merge WI-000320 to QA

---

force-app/main/default/flexipages/Proceeding_Record_Page1.flexipage-meta.xml

[DevOps Center] Merge WI-000323 to QA

---

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_Application_Created_Year__c.field-meta.xml

[DevOps Center] Merge WI-000324 to QA

---

force-app/main/default/layouts/Contact-Contact Layout.layout-meta.xml

[DevOps Center] Merge WI-000326 to QA

---

force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000328 to QA

---

force-app/main/default/aura/GeneratePDF/GeneratePDF.cmp
force-app/main/default/aura/GeneratePDF/GeneratePDF.design
force-app/main/default/aura/GeneratePDF/GeneratePDFController.js
force-app/main/default/flows/CVRD_DS_Application_Reconsideration_Letter.flow-meta.xml
force-app/main/default/flows/Upload_Submission_Requests.flow-meta.xml

[DevOps Center] Merge WI-000315 to QA

---

force-app/main/default/flows/CVRD_DS_Additional_Fee_Flow.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Application_Journey.flow-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Units__c.field-meta.xml

[DevOps Center] Merge WI-000329 to QA

---

force-app/main/default/layouts/MUSW__Application2__c-clariti__Application Experience.layout-meta.xml

[DevOps Center] Merge WI-000331 to QA

---

force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000332 to QA

---

force-app/main/default/flows/CVRD_DS_Create_Application_Location_Record.flow-meta.xml

[DevOps Center] Merge WI-000333 to QA

---

force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000336 to QA

---

force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_Approval.approvalProcess-meta.xml
force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_General_Manager_V2.approvalProcess-meta.xml
force-app/main/default/globalValueSets/CVRD_DS_Sub_Type.globalValueSet-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Sub_Type__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Cannabis_License.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Liquor_Cannabis_Licence_Referrals.recordType-meta.xml
force-app/main/default/objects/MUSW__Master_Fee_List__c/recordTypes/MUSW__Application_Fee.recordType-meta.xml

[DevOps Center] Merge WI-000337 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Journey.flow-meta.xml
force-app/main/default/layouts/MUSW__Application_Contact__c-MUSW__Application Contact Layout.layout-meta.xml

[DevOps Center] Merge WI-000338 to QA

---

force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000339 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Journey.flow-meta.xml
force-app/main/default/layouts/MUSW__Application2__c-CVRD DS Strata Community Layout.layout-meta.xml

[DevOps Center] Merge WI-000340 to QA

---

force-app/main/default/flows/CVRD_DS_Additional_Fee_Flow.flow-meta.xml

[DevOps Center] Merge WI-000341 to QA

---

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Units__c.field-meta.xml

[DevOps Center] Merge WI-000342 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Reconsideration_Letter.flow-meta.xml
force-app/main/default/layouts/MUSW__Application2__c-CVRD DS APplication Layout.layout-meta.xml

[DevOps Center] Merge WI-000343 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Reconsideration_Letter.flow-meta.xml

[DevOps Center] Merge WI-000344 to QA

---

force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000345 to QA

---

force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml
force-app/main/default/flows/CVRD_DS_Create_Application_Location_Record.flow-meta.xml

[DevOps Center] Merge WI-000346 to QA

---

force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_Approval_V2.approvalProcess-meta.xml

[DevOps Center] Merge WI-000347 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Journey.flow-meta.xml

[DevOps Center] Merge WI-000351 to QA

---

force-app/main/default/layouts/Task-Referral External Agency Task Layout.layout-meta.xml

[DevOps Center] Merge WI-000352 to QA

---

force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000363 to QA

---

force-app/main/default/layouts/MUSW__Application2__c-MUSW__Application Layout.layout-meta.xml
force-app/main/default/layouts/MUSW__Application2__c-clariti__Application Experience.layout-meta.xml
force-app/main/default/profiles/CVRD Citizen Login User.profile-meta.xml
force-app/main/default/profiles/CVRD Citizenship Portal User Profile.profile-meta.xml

[DevOps Center] Merge WI-000364 to QA

---

force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/routes/applicationDetail.json
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/applicationDetail.json
force-app/main/default/layouts/MUSW__Application2__c-MUSW__Application Layout.layout-meta.xml
force-app/main/default/layouts/MUSW__Application2__c-clariti__Application Experience.layout-meta.xml
force-app/main/default/profiles/CVRD Citizenship Portal User Profile.profile-meta.xml

[DevOps Center] Merge WI-000365 to QA

---

force-app/main/default/objects/MUSW__Application2__c/validationRules/Read_only_for_Application_Number.validationRule-meta.xml

[DevOps Center] Merge WI-000369 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Complete_Hearing_Phase.flow-meta.xml
force-app/main/default/layouts/MUSW__Application_Contact__c-MUSW__Application Contact Layout.layout-meta.xml
force-app/main/default/quickActions/MUSW__Application2__c.Complete_Hearing.quickAction-meta.xml

[DevOps Center] Merge WI-000370 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Journey.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Confirm_and_create_Application.flow-meta.xml

[DevOps Center] Merge WI-000371 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Complete_Hearing_Phase.flow-meta.xml

[DevOps Center] Merge WI-000372 to QA

---

force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_General_Manager_V2.approvalProcess-meta.xml
force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml
force-app/main/default/flows/CVRD_DS_Application_Journey.flow-meta.xml

[DevOps Center] Merge WI-000374 to QA

---

force-app/main/default/flows/CVRD_DS_Application_Journey.flow-meta.xml

[DevOps Center] Merge WI-000375 to QA

---

force-app/main/default/objects/MUSW__Proceeding2__c/compactLayouts/MUSW__Proceeding_Default.compactLayout-meta.xml

[DevOps Center] Merge WI-000376 to QA

---

force-app/main/default/flows/CVRD_DS_Update_Planner_Review_to_Correction_Required.flow-meta.xml
force-app/main/default/layouts/MUSW__Milestone__c-MUSW__Milestone Admin Review.layout-meta.xml
force-app/main/default/layouts/MUSW__Milestone__c-MUSW__Milestone Plan Review.layout-meta.xml
force-app/main/default/layouts/MUSW__Review__c-Application - Review Layout.layout-meta.xml

[DevOps Center] Merge WI-000378 to QA

---

force-app/main/default/flows/CVRD_DS_Create_Proceeding_Agenda_Item.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Update_Agenda_Item_OutCome.flow-meta.xml

[DevOps Center] Merge WI-000379 to QA

---

force-app/main/default/classes/CVRD_DS_PublicSearchController.cls
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/electoralAreaB.json
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/electoralAreaC.json
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/electoralAreaD.json
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/electoralAreaE.json
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/electoralAreaF.json
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/electoralAreaG.json
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/electoralAreaH.json
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/electoralAreaI.json
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/openSearch.json
force-app/main/default/lwc/cVRD_DS_DocumentAvailablePublicly/cVRD_DS_DocumentAvailablePublicly.html
force-app/main/default/lwc/cVRD_DS_DocumentAvailablePublicly/cVRD_DS_DocumentAvailablePublicly.js
force-app/main/default/lwc/cVRD_DS_PublicApplicationSearch/cVRD_DS_PublicApplicationSearch.css
force-app/main/default/lwc/cVRD_DS_PublicApplicationSearch/cVRD_DS_PublicApplicationSearch.html
force-app/main/default/lwc/cVRD_DS_PublicApplicationSearch/cVRD_DS_PublicApplicationSearch.js
force-app/main/default/lwc/cVRD_DS_PublicApplicationSearch/cVRD_DS_PublicApplicationSearch.js-meta.xml

[DevOps Center] Merge WI-000377 to QA

---

force-app/main/default/objects/MUSW__Master_Submission_List__c/recordTypes/MUSW__Application_Submission.recordType-meta.xml

[DevOps Center] Merge WI-000382 to QA

---

force-app/main/default/flows/Upload_Submission_Requests.flow-meta.xml

[DevOps Center] Merge WI-000381 to QA

---

force-app/main/default/flows/CVRD_DS_Update_Agenda_Item_OutCome.flow-meta.xml
force-app/main/default/lwc/cVRD_DS_DocumentAvailablePublicly/cVRD_DS_DocumentAvailablePublicly.html
force-app/main/default/lwc/cVRD_DS_DocumentAvailablePublicly/cVRD_DS_DocumentAvailablePublicly.js
force-app/main/default/lwc/cVRD_DS_Proceeding_Details/cVRD_DS_Proceeding_Details.html
force-app/main/default/lwc/cVRD_DS_Proceeding_Details/cVRD_DS_Proceeding_Details.js
force-app/main/default/lwc/cVRD_DS_PublicApplicationSearch/cVRD_DS_PublicApplicationSearch.html
force-app/main/default/lwc/cVRD_DS_PublicApplicationSearch/cVRD_DS_PublicApplicationSearch.js
force-app/main/default/navigationMenus/Electoral_Area.navigationMenu-meta.xml

[DevOps Center] Merge WI-000380 to QA

---

force-app/main/default/profiles/CVRD Citizen Login User.profile-meta.xml

[DevOps Center] Merge WI-000384 to QA

---

force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/taskDetail.json

[DevOps Center] Merge WI-000386 to QA

---

force-app/main/default/flows/CVRD_DS_Update_Agenda_Item_OutCome.flow-meta.xml
force-app/main/default/layouts/MUSW__Application2__c-Guest Layout.layout-meta.xml
force-app/main/default/lwc/cVRD_DS_DocumentAvailablePublicly/cVRD_DS_DocumentAvailablePublicly.html
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Email__c.field-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/CVRD Citizenship Portal User Profile.profile-meta.xml

[DevOps Center] Merge WI-000383 to QA

---

force-app/main/default/flexipages/Account_Record_Page1.flexipage-meta.xml
force-app/main/default/layouts/Contact-Contact Layout.layout-meta.xml

[DevOps Center] Merge WI-000395 to QA

---

force-app/main/default/aura/loginForm/loginForm.cmp
force-app/main/default/aura/loginForm/loginForm.cmp-meta.xml
force-app/main/default/aura/loginForm/loginForm.css
force-app/main/default/aura/loginForm/loginForm.design
force-app/main/default/aura/loginForm/loginFormController.js
force-app/main/default/aura/loginForm/loginFormHelper.js

[DevOps Center] Merge WI-000399 to QA org

---

force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml
force-app/main/default/flows/Application_Journey.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Update_Application_to_CloseOut.flow-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Subdivision_Referral.recordType-meta.xml

[DevOps Center] Merge WI-000400 to QA

---

force-app/main/default/flows/User_Registration.flow-meta.xml
force-app/main/default/lwc/cVRD_DS_RepatchaLwc/cVRD_DS_RepatchaLwc.css
force-app/main/default/lwc/cVRD_DS_RepatchaLwc/cVRD_DS_RepatchaLwc.html
force-app/main/default/lwc/cVRD_DS_RepatchaLwc/cVRD_DS_RepatchaLwc.js
force-app/main/default/lwc/cVRD_DS_RepatchaLwc/cVRD_DS_RepatchaLwc.js-meta.xml

[DevOps Center] Merge WI-000401 to QA

---

force-app/main/default/profiles/CVRD Citizen Login User.profile-meta.xml
force-app/main/default/profiles/CVRD DM.profile-meta.xml
force-app/main/default/profiles/CVRD DS Admin.profile-meta.xml
force-app/main/default/profiles/CVRD DS Staff.profile-meta.xml
force-app/main/default/profiles/CVRD GM.profile-meta.xml
force-app/main/default/profiles/CVRD System Admin.profile-meta.xml

[DevOps Center] Merge WI-000404 to QA

---

force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000405 to QA

---

force-app/main/default/customMetadata/clariti__PaymentMethod.Cheque.md-meta.xml
force-app/main/default/customMetadata/clariti__PaymentMethod.Letter_of_Credit.md-meta.xml
force-app/main/default/customMetadata/clariti__PaymentMethod.debit_card.md-meta.xml

[DevOps Center] Merge WI-000402 to QA

---

force-app/main/default/staticresources/GISWidgets/widgets/configs/LayerList2/config_LayerList2.json

[DevOps Center] Merge WI-000406 to QA

---

force-app/main/default/flows/CVRD_DS_Create_Application_Location_Record.flow-meta.xml

[DevOps Center] Merge WI-000409 to QA

---

force-app/main/default/flows/CVRD_DS_Create_Public_Notice.flow-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/CVRD Citizenship Portal User Profile.profile-meta.xml

[DevOps Center] Merge WI-000410 to QA

---

force-app/main/default/profiles/CVRD Citizen Login User.profile-meta.xml

[DevOps Center] Merge WI-000411 to QA

---

force-app/main/default/profiles/Admin.profile-meta.xml

[DevOps Center] Merge WI-000414 to QA

---

force-app/main/default/audience/Applicant_Portal.audience-meta.xml
force-app/main/default/audience/Applicant_Portal1.audience-meta.xml
force-app/main/default/audience/Default_CVRD Citizenship Portal User.audience-meta.xml
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/themes/claritiCommunityPortal.json
force-app/main/default/flows/CVRD_DS_Application_Journey.flow-meta.xml
force-app/main/default/profiles/CVRD Citizenship Portal User Profile.profile-meta.xml

[DevOps Center] Merge WI-000418 to DSTraining Org

---

force-app/main/default/aura/GeneratePDF/GeneratePDFController.js
force-app/main/default/customMetadata/clariti__PaymentMethod.clariti__AccountCredit.md-meta.xml
force-app/main/default/customMetadata/clariti__PaymentMethod.clariti__Cash.md-meta.xml
force-app/main/default/customMetadata/clariti__PaymentMethod.clariti__SecurityDeposit.md-meta.xml
force-app/main/default/customMetadata/clariti__PaymentMethod.clariti__TrustAccount.md-meta.xml
force-app/main/default/flows/CVRD_DS_Application_Journey.flow-meta.xml
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Sub_Type__c.field-meta.xml

[DevOps Center] Merge WI-000419 to DSTraining Org

---

force-app/main/default/aura/GeneratePDF/GeneratePDF.cmp
force-app/main/default/aura/GeneratePDF/GeneratePDF.design
force-app/main/default/aura/GeneratePDF/GeneratePDFController.js

[DevOps Center] Merge WI-000421 to DSTraining Org

---

force-app/main/default/aura/cVRD_ResumeApplication/cVRD_ResumeApplication.cmp
force-app/main/default/aura/cVRD_ResumeApplication/cVRD_ResumeApplicationHelper.js
force-app/main/default/classes/CVRD_DS_Split_MultiPicklist.cls
force-app/main/default/customMetadata/clariti__PaymentMethod.DebitCard.md-meta.xml
force-app/main/default/customMetadata/clariti__PaymentMethod.LetterOfCredit.md-meta.xml
force-app/main/default/customMetadata/clariti__PaymentMethod.clariti__Check.md-meta.xml
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/myPausedApplications.json
force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml
force-app/main/default/flows/CVRD_DS_AccountId_Update_from_Applicant_s_Account.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Create_Fee_Application.flow-meta.xml
force-app/main/default/lwc/cVRD_Override_Flow_Buttons/cVRD_Override_Flow_Buttons.js
force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Sub_Type__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Temporary_Use_Permit.recordType-meta.xml
force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Completed_Action__c.field-meta.xml
force-app/main/default/objects/MUSW__Review__c/validationRules/CVRD_DS_Completed_Approved.validationRule-meta.xml
force-app/main/default/profiles/CVRD Citizen Login User.profile-meta.xml

[DevOps Center] Merge WI-000420 to DSTraining Org

---

force-app/main/default/flows/CVRD_DS_Create_Proceeding_Agenda_Item.flow-meta.xml

[DevOps Center] Merge WI-000423 to DSTraining Org

---

force-app/main/default/applications/MUSW__PlanningConsole.app-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml

[DevOps Center] Merge WI-000424 to DSTraining Org

---

force-app/main/default/flows/CVRD_DS_Task_Due_Date_Email_Notification_for_Referrals.flow-meta.xml
force-app/main/default/labels/CustomLabels.labels-meta.xml
force-app/main/default/objects/MUSW__Application2__c/listViews/MUSW__All.listView-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/CVRD DS Admin.profile-meta.xml
force-app/main/default/profiles/CVRD DS Staff.profile-meta.xml

[DevOps Center] Merge WI-000425 to DSTraining Org

---

force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/CVRD DS Admin.profile-meta.xml
force-app/main/default/profiles/CVRD DS Staff.profile-meta.xml

[DevOps Center] Merge WI-000427 to DSTraining Org

---

force-app/main/default/layouts/MUSW__Application2__c-CVRD DS App Experience without Environmental Riparian.layout-meta.xml
force-app/main/default/profiles/CVRD Citizen Login User.profile-meta.xml
force-app/main/default/profiles/CVRD DS External Referral Profile User.profile-meta.xml

[DevOps Center] Merge WI-000429 to DSTraining Org

---

force-app/main/default/flows/CVRD_DS_AccountId_Update_from_Applicant_s_Account.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Confirm_and_create_Application.flow-meta.xml
force-app/main/default/objects/MUSW__Application2__c/validationRules/CVRD_DS_Application_Planner_is_required.validationRule-meta.xml
force-app/main/default/objects/MUSW__Review__c/validationRules/CVRD_DS_Review_Planner_is_Required.validationRule-meta.xml

[DevOps Center] Merge WI-000431 to DSTraining Org

---

force-app/main/default/flows/Application_Create_Submissions.flow-meta.xml

[DevOps Center] Merge WI-000432 to DSTraining Org

---

force-app/main/default/flows/Upload_Submission_Requests.flow-meta.xml

[DevOps Center] Merge WI-000433 to DSTraining Org

---

force-app/main/default/flows/CVRD_DS_Fee_update_with_Ledger_account.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Update_Agenda_Item_OutCome.flow-meta.xml
force-app/main/default/layouts/Task-Referral External Agency Task Layout.layout-meta.xml
force-app/main/default/lwc/cVRD_DS_Proceeding_Details/cVRD_DS_Proceeding_Details.html
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/CVRD DS External Referral Profile User.profile-meta.xml
force-app/main/default/profiles/CVRD DS Staff.profile-meta.xml

[DevOps Center] Merge WI-000437 to DSTraining Org

---

force-app/main/default/classes/CVRD_DS_PublicSearchController.cls
force-app/main/default/objects/Case/fields/CVRD_DS_Public_Comment__c.field-meta.xml
force-app/main/default/profiles/CVRD Citizen Login User.profile-meta.xml

[DevOps Center] Merge WI-000438 to DSTraining Org

---

force-app/main/default/profiles/CVRD DS System Admin.profile-meta.xml

[DevOps Center] Merge WI-000440 to DSTraining Org

---

force-app/main/default/profiles/Admin.profile-meta.xml

[DevOps Center] Merge WI-000444 to DSTraining Org

---

force-app/main/default/profiles/CVRD DM.profile-meta.xml
force-app/main/default/profiles/CVRD DS Admin.profile-meta.xml
force-app/main/default/profiles/CVRD DS Staff.profile-meta.xml
force-app/main/default/profiles/CVRD DS System Admin.profile-meta.xml
force-app/main/default/profiles/CVRD GM.profile-meta.xml

[DevOps Center] Merge WI-000445 to DSTraining Org

---

force-app/main/default/flows/CVRD_DS_Application_Complete_Hearing_Phase.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Confirm_and_create_Application.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Update_Application_to_CloseOut.flow-meta.xml
force-app/main/default/objects/MUSW__Condition__c/fields/CVRD_DS_Type__c.field-meta.xml

[DevOps Center] Merge WI-000446 to DSTraining Org

---

force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml
force-app/main/default/flows/CVRD_DS_Create_Application_Location_Record.flow-meta.xml

[DevOps Center] Merge WI-000447 to DSTraining Org

---

force-app/main/default/approvalProcesses/MUSW__Application2__c.CVRD_DS_Application_General_Manager_V2.approvalProcess-meta.xml
force-app/main/default/flows/Application_Journey.flow-meta.xml
force-app/main/default/workflows/MUSW__Application2__c.workflow-meta.xml

[DevOps Center] Merge WI-000449 to DSTraining Org

---

force-app/main/default/applications/MUSW__PlanningConsole.app-meta.xml
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/routes/askAQuestion.json
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/askAQuestion.json
force-app/main/default/experiences/CVRD_Citizenship_Portal_User1/views/taskDetail.json
force-app/main/default/flows/CVRD_DS_Ask_a_question.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Submission_Status_Change.flow-meta.xml
force-app/main/default/navigationMenus/Citizen_Menu.navigationMenu-meta.xml
force-app/main/default/profiles/CVRD DS Staff.profile-meta.xml

[DevOps Center] Merge WI-000451 to DSTraining Org

---

force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.ALR_EASC_V2.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.ALR_SEASC_V2.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.COV_EASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.COV_SEASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.CRL_EASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.CRL_SEASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.DP_EASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.DP_SEASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.DVP_EASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.DVP_SEASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.FB_EASC_V3.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.FB_SEASC_V3.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.LR_EASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.LR_SEASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.MF_EASC_V3.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.MF_SEASC_V3.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.OCP_EASC_V10.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.OCP_SEASC_V10.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.PDA_EASC_V10.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.PDA_SEASC_V10.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.SC_EASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.SC_SEASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.TEL_EASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.TEL_SEASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.TUP_EASC_V4.md-meta.xml
force-app/main/default/customMetadata/CVRD_DS_Proceeding_OutcomeMapping.TUP_SEASC_V4.md-meta.xml
force-app/main/default/flows/CVRD_DS_Create_Proceeding_Agenda_Item.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Update_Agenda_Item_OutCome.flow-meta.xml
force-app/main/default/objects/CVRD_DS_Proceeding_OutcomeMapping__mdt/fields/CVRD_DS_OutcomeValue__c.field-meta.xml
force-app/main/default/objects/MUSW__Proceeding_Agenda_Item__c/fields/CVRD_DS_Outcome__c.field-meta.xml

[DevOps Center] Merge WI-000453 to DSTraining Org

---

force-app/main/default/profiles/CVRD DM.profile-meta.xml
force-app/main/default/profiles/CVRD DS Admin.profile-meta.xml
force-app/main/default/profiles/CVRD DS Staff.profile-meta.xml
force-app/main/default/profiles/CVRD DS System Admin.profile-meta.xml
force-app/main/default/profiles/CVRD GM.profile-meta.xml

[DevOps Center] Merge WI-000456 to DSTraining Org

---

force-app/main/default/classes/CVRD_DS_PublicSearchController.cls
force-app/main/default/flows/CVRD_DS_Ask_a_question.flow-meta.xml
force-app/main/default/flows/CVRD_DS_Update_Fee_paid_Date.flow-meta.xml
force-app/main/default/lwc/cVRD_DS_PublicApplicationSearch/cVRD_DS_PublicApplicationSearch.js

[DevOps Center] Merge WI-000452 to DSTraining Org

---

force-app/main/default/objects/MUSW__Application2__c/fields/CVRD_DS_Application_Status__c.field-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Agricultural_Land_Reserve.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Board_of_Variance.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Cannabis_License.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Covenant_Amendment_or_Discharge.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Development_Permit.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Development_Variance_Permit.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Flood_Management_Bylaw_Exemption.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Land_Use_Contract_Amendment_or_Discharge.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Liquor_Cannabis_Licence_Referrals.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Minimum_Frontage_Exemption.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_OCP_Zoning_or_Land_Use_Bylaw_Amendment.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Phased_Development_Agreement.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Strata_Conversion.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Subdivision_Referral.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Telecommunication_Antenna_Structure.recordType-meta.xml
force-app/main/default/objects/MUSW__Application2__c/recordTypes/CVRD_DS_Temporary_Use_Permit.recordType-meta.xml

[DevOps Center] Merge WI-000458 to DSTraining Org

---

force-app/main/default/flexipages/CVRD_DS_Application_Record_Page.flexipage-meta.xml
force-app/main/default/layouts/MUSW__Application2__c-CVRD DS APplication Layout.layout-meta.xml
force-app/main/default/layouts/MUSW__Application2__c-CVRD DS Strata Community Layout.layout-meta.xml
force-app/main/default/layouts/MUSW__Application2__c-Guest Layout.layout-meta.xml
force-app/main/default/layouts/MUSW__Application2__c-clariti__Application Experience.layout-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/CVRD Citizen Login User.profile-meta.xml
force-app/main/default/profiles/CVRD Citizenship Portal User Profile.profile-meta.xml
force-app/main/default/profiles/CVRD DM.profile-meta.xml
force-app/main/default/profiles/CVRD DS Admin.profile-meta.xml
force-app/main/default/profiles/CVRD DS Internal Referral Profile User.profile-meta.xml
force-app/main/default/profiles/CVRD DS Staff.profile-meta.xml
force-app/main/default/profiles/CVRD DS System Admin.profile-meta.xml
force-app/main/default/profiles/CVRD GM.profile-meta.xml

[DevOps Center] Merge WI-000459 to DSTraining Org
